openapi: 3.0.2
info:
  version: "1.0.0"
  title: "Scada API"
  description: "Scada API"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: https://beta2-api.dforcepro.com/buyer
    description: 開發站

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT