openapi: 3.0.0
info:
  version: 1.0.0
  title: Scada-Auth-Api
  description: scada授權服務功能規格

paths:
  /v1/login:
    post:
      summary: 登入
      operationId: login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                account:
                  type: string
                  description: 使用者帳號
                  example: gavin
                pwd:
                  type: string
                  description: 密碼
                  example: 1234
      responses:
        '200':
          description: 回傳使用者Token，做API使用者驗證
          content:
            application/json:
              schema:
                type: object
                properties:
                  refresh:
                    type: string
                    description: refresh token
                  token:
                    type: string
                    description: access token
                  permission:
                    type: string
                    enum: [user, admin]
                    description: 權限
                example:
                  refresh: 85NIXszWOzL6oSJuSdIMBOCSOnQHrOqeROfAy_vAwtyU9Asd2t9PE9WDubG0YNceb8czjmeQxDNj2uS_mC6YiNAwmOUkfgVeQnuM8xiItKM4qTwkWFSOHIqrn7UqyggJGYosA-ilF9PpKBRiqm-EKvS_ptioNQHe3wtDHJS1YgpXtGtzoyIamCVBxUXJSukczRdKfh5xjdtD-1zDOVsHWM6WUkhfGUK1qew-vgSuXBiT0uEzqpDLt-mawQqDH3kZgiReTc3mmxkSlY2Eiq5Z6yf6UyCkpnd_C0R3lEe6rw==
                  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1sLXY1IiwidHlwIjoiSldUIn0.eyJleHAiOjE3MTY4ODE0ODAsImlhdCI6MTcxNjg3Nzg4MCwiaXNzIjoibG9jYWxob3N0OjIwODAiLCJwZXIiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.DAqGvadU3WPoGTfGoAL4s1DBVZi1V0ocpYO3M4jjbRDnZ8OzXs9riV8Zc7uUIeqWi9tINzVbTKos1j1j1Fi7zt9E8o7k41_KeVdgRKL8cnnzaypmocg4y4NLwdXZEyl0svN9X1VBq2kMoRlxxqXTQstDiSLtW8iIFNkt518zB9R8jSgaswH4srYGXYJjOs7maq4o8etjQKgHBA-6UMR3OrgkALt3W_5z3SGM3wSg-HX8a0K3CSzr_MAaOJbozLmq5jGktTFjZAGIoMxI29VE-5HpMIRecKMLB6CW84gO9527cVpLWG3uiH-URT1jwr3_oQHO_ycpExThvLK71WUugw
                  permission: user
        '400':
          description: 無效的輸入
        '404':
          description: 使用者帳號或密碼錯誤
        '500':
          description: 伺服器發生錯誤
  /v1/pwd:
    put:
      summary: 修改密碼
      operationId: change-password
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                old:
                  type: string
                  description: 舊使用者帳號
                  example: 1234
                new:
                  type: string
                  description: 新密碼
                  example: 5678
      responses:
        '200':
          description: ok
        '400':
          description: invalid password
        '500':
          description: interval server error
  /v1/token/remote:
    post:
      summary: 取得遠端控制Token
      operationId: get-remote-token
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                pwd:
                  type: string
                  description: 使用者帳號
                  example: 1234
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: 身份驗證
                example:
                  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1sLXY1IiwidHlwIjoiSldUIn0.eyJleHAiOjE3MTY4ODE0ODAsImlhdCI6MTcxNjg3Nzg4MCwiaXNzIjoibG9jYWxob3N0OjIwODAiLCJwZXIiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.DAqGvadU3WPoGTfGoAL4s1DBVZi1V0ocpYO3M4jjbRDnZ8OzXs9riV8Zc7uUIeqWi9tINzVbTKos1j1j1Fi7zt9E8o7k41_KeVdgRKL8cnnzaypmocg4y4NLwdXZEyl0svN9X1VBq2kMoRlxxqXTQstDiSLtW8iIFNkt518zB9R8jSgaswH4srYGXYJjOs7maq4o8etjQKgHBA-6UMR3OrgkALt3W_5z3SGM3wSg-HX8a0K3CSzr_MAaOJbozLmq5jGktTFjZAGIoMxI29VE-5HpMIRecKMLB6CW84gO9527cVpLWG3uiH-URT1jwr3_oQHO_ycpExThvLK71WUugw
        '400':
          description: invalid password
        '500':
          description: interval server error
  /v1/token/refresh:
    get:
      summary: 更新access token
      operationId: refresh-token
      parameters:
        - name: refresh_token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: 身份驗證
                example:
                  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1sLXY1IiwidHlwIjoiSldUIn0.eyJleHAiOjE3MTY4ODE0ODAsImlhdCI6MTcxNjg3Nzg4MCwiaXNzIjoibG9jYWxob3N0OjIwODAiLCJwZXIiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.DAqGvadU3WPoGTfGoAL4s1DBVZi1V0ocpYO3M4jjbRDnZ8OzXs9riV8Zc7uUIeqWi9tINzVbTKos1j1j1Fi7zt9E8o7k41_KeVdgRKL8cnnzaypmocg4y4NLwdXZEyl0svN9X1VBq2kMoRlxxqXTQstDiSLtW8iIFNkt518zB9R8jSgaswH4srYGXYJjOs7maq4o8etjQKgHBA-6UMR3OrgkALt3W_5z3SGM3wSg-HX8a0K3CSzr_MAaOJbozLmq5jGktTFjZAGIoMxI29VE-5HpMIRecKMLB6CW84gO9527cVpLWG3uiH-URT1jwr3_oQHO_ycpExThvLK71WUugw
        '400':
          description: invalid token
        '500':
          description: interval server error
  /v1/register:
    post:
      summary: 使用者註冊
      operationId: register
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                account:
                  type: string
                  description: 使用者帳號
                  example: admin
                pwd:
                  type: string
                  description: 密碼
                  example: 1234
                perm:
                  type: string
                  description: 權限
                  enum: [user, admin]
                key:
                  type: string
                  description: 驗證碼
                  example: 1234
      responses:
        '200':
          description: ok
        '400':
          description: invalid password
        '500':
          description: interval server error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
