openapi: 3.0.2
info:
  version: "1.0.0"
  title: "Communicate_To_Sacada_Service"
  description: "subscribe communicate data and persitence to sacada"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /v1/sse/{FLOOR_ID}:
    get:
      summary: "Floor-SSE"
      description: "Floor-SSE"
      operationId: "get-sse"
      security:
        - BearerAuth: []
      parameters:
      - name: FLOOR_ID
        in: path
        description: String ID of the tv
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "SSE"
          content:
            'text/event-stream':
              schema:
                type: object
                additionalProperties:
                  type: string
                example:
                  10100@1F_engine_AVD101: 12.4
                  10101@1F_engine_AVD101: -2.8
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT